### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Huster-Hq** [soleilssss/FFCNet#2]
作者您好，FFCNet/model.py中第74行代码应该有些问题

**Comment by soleilssss** [comment]
你好，74行没什么问题呀，请问您具体指的是什么发自我的手机-------- 原始邮件 --------发件人： Huster-Hq ***@***.***>日期： 2023年2月10日周五 下午4:05收件人： soleilssss/FFCNet ***@***.***>抄送： Subscribed ***@***.***>主    题： [soleilssss/FFCNet] error (Issue #2)

作者您好，FFCNet/model.py中第74行代码应该有些问题
